export { EfetivoDashboard } from "./EfetivoDashboard"
export { CustosDashboard } from "./CustosDashboard"
export { MedicaoDashboard } from "./MedicaoDashboard"
export { OrcamentoDashboard } from "./OrcamentoDashboard"
export { CrossAnalysisDashboard } from "./CrossAnalysisDashboard"
export { TemplateSelection } from "./TemplateSelection"
export { UploadZone } from "./UploadZone"

export { AnomaliasDashboard } from "./AnomaliasDashboard"
export { TendenciasDashboard } from "./TendenciasDashboard"
export { SegmentacaoDashboard } from "./SegmentacaoDashboard"
export { ClusteringDashboard } from "./ClusteringDashboard"
export { ProfilerDashboard } from "./ProfilerDashboard"
export { ExportarView } from "./ExportarView"
